name: flutter_test_shop_firebase
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Functional Programming
  dartz: ^0.9.1

  #State Management
  flutter_riverpod: ^0.12.4
  equatable: ^1.2.6
  freezed_annotation: ^0.12.0
  flutter_hooks: ^0.15.0

  #Firebase
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0

  cupertino_icons: ^1.0.0

  errors:
    git:
      url: git://github.com/NoScopeDevs/errors
  network_manager:
    git:
      url: git://github.com/NoScopeDevs/network_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: null
  build_runner: null

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
